# Profil par défaut pour le développement local
spring.profiles.active=dev

# Configuration commune à tous les environnements
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

# --- Configuration pour le profil 'dev' (H2) ---
# Ces propriétés sont actives par défaut. Elles seront écrasées en production.

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true